# Generated by Django 2.2.4 on 2019-08-27 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 3', regex='^.{3}$')]),
        ),
    ]
