app:
  address: ""
  port: 3000
database:
  dialect: "mysql"
  address: "db"
  username: "docker"
  password: "docker"
  name: "currency"
  port: 3306
  charset: "utf8"
Redis:
  address: "redis"
  port: 6379